[package]
name = "nexmark"
version = "0.1.0"
edition = "2021"
description = "Nexmark data stream generator."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
bin = ["clap", "serde", "serde_json"]

[dependencies]
clap = { version = "3", features = ["derive"], optional = true }
lazy_static = "1.4"
rand = { version = "0.8", features = ["small_rng"] }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "gen"
harness = false

[[bin]]
name = "nexmark"
required-features = ["bin"]
