[package]
name = "risingwave_connector"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1"
async-stream = "0.3"
async-trait = "0.1"
aws-config = { workspace = true } 
aws-sdk-kinesis = { workspace = true } 
aws-sdk-s3 = { workspace = true } 
aws-sdk-sqs = { workspace = true } 
aws-smithy-http = { workspace = true }
aws-smithy-types = { workspace = true }
aws-types = { workspace = true }
byteorder = "1"
bytes = { version = "1", features = ["serde"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
crc32fast = "1"
either = "1"
enum-as-inner = "0.5"
farmhash = "1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = "0.2"
futures-concurrency = "3"
globset = "0.4.8"
http = "0.2"
http-serde = "1.1.0"
humantime = "2.1"
hyper = "0.14"
itertools = "0.10"
maplit = "1.0.2"
memcomparable = { path = "../utils/memcomparable" }
mysql_async = "0.31"
nexmark = { path = "../utils/nexmark", features = ["serde"] }
num-traits = "0.2"
paste = "1"
prost = "0.11"
pulsar = { version = "4.2", default-features = false, features = ["tokio-runtime"] }
rand = "0.8"
rdkafka = { package = "madsim-rdkafka", version = "=0.2.8-alpha", features = ["cmake-build", "ssl-vendored", "gssapi"] }
risingwave_common = { path = "../common" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
risingwave_storage = { path = "../storage" }
serde = { version = "1", features = ["derive", "rc"] }
serde_derive = "1"
serde_json = "1"
serde_with = "2"
smallvec = "1"
static_assertions = "1"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
tempfile = "3"
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = ["rt", "rt-multi-thread", "sync", "macros", "time", "signal", "fs"] }
tokio-retry = "0.3"
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["codec", "io"] }
tonic = { version = "0.2", package = "madsim-tonic" }
tracing = "0.1"
twox-hash = "1"
url = "2"
urlencoding = "2"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
rand = "0.8"
rust_decimal = "1"
tempfile = "3"
wiremock = "0.5"
