[package]
name = "risingwave_ctl"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1"
bytes = "1"
chrono = "0.4"
clap = { version = "3", features = ["derive"] }
comfy-table = "6"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
itertools = "0.10"
parking_lot = "0.12"
regex = "1.6.0"
risingwave_common = { path = "../common" }
risingwave_common_service = { path = "../common/common_service" }
risingwave_frontend = { path = "../frontend" }
risingwave_hummock_sdk = { path = "../storage/hummock_sdk" }
risingwave_object_store = { path = "../object_store" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
risingwave_storage = { path = "../storage" }
risingwave_stream = { path = "../stream" }
serde_json = "1"
size = "0.4"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../workspace-hack" }
