[package]
name = "risingwave_planner_test"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
console = "0.15"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
itertools = "0.10"
libtest-mimic = "0.6"
risingwave_frontend = { path = ".." }
risingwave_sqlparser = { path = "../../sqlparser" }
serde = { version = "1", features = ["derive"] }
serde_with = "2"
serde_yaml = "0.9"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
walkdir = "2"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]
tempfile = "3"

[build-dependencies]
anyhow = "1"
walkdir = "2"

[[bin]]
name = "planner-test-apply"
path = "src/bin/apply.rs"

[[test]]
name = "planner_test_runner"
harness = false
