[meta]
min_sst_retention_time_sec = 0
collect_gc_watermark_spin_interval_sec = 1
vacuum_interval_sec = 10

[backup]
storage_url = "minio://hummockadmin:hummockadmin@127.0.0.1:9301/hummock001"
storage_directory = "backup"
