[package]
name = "risingwave_hummock_test"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bytes = { version = "1" }
clap = { version = "4", features = ["derive"] }
fail = "0.5"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
itertools = "0.10"
parking_lot = "0.12"
rand = "0.8"
risingwave_common = { path = "../../common" }
risingwave_common_service = { path = "../../common/common_service" }
risingwave_compute = { path = "../../compute" }
risingwave_hummock_sdk = { path = "../hummock_sdk" }
risingwave_hummock_trace = { path = "../hummock_trace" }
risingwave_meta = { path = "../../meta", features = ["test"] }
risingwave_object_store = { path = "../../object_store" }
risingwave_pb = { path = "../../prost" }
risingwave_rpc_client = { path = "../../rpc_client" }
risingwave_storage = { path = "..", features = ["test"] }
serde = { version = "1", features = ["derive"] }
tokio = { version = "0.2", package = "madsim-tokio" }

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["alloc", "executor"] }
risingwave_test_runner = { path = "../../test_runner" }
serial_test = "0.9"
sync-point = { path = "../../utils/sync-point" }

[features]
failpoints = ["risingwave_storage/failpoints"]
sync_point = ["sync-point/sync_point"]

[[bin]]
name = "replay"
path = "src/bin/replay/main.rs"
