[package]
name = "risingwave_hummock_trace"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
bincode = { version = "=2.0.0-rc.2", features = ["serde"] }
byteorder = "1"
either = "1"
flume = "0.10.14"
lazy_static = "1.4.0"
parking_lot = "0.12"
risingwave_common = { path = "../../common" }
risingwave_pb = { path = "../../prost" }
ron = "0.8"
thiserror = "1.0"
tokio = { version = "0.2", package = "madsim-tokio" }

[dev-dependencies]
mockall = "0.11.2"
