[package]
name = "risedev"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1"
bytes = "1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap = { version = "3", features = ["derive"] }
console = "0.15"
dialoguer = "0.10"
enum-iterator = "1"
indicatif = "0.17"
isahc = { version = "1", default-features = false, features = ["text-decoding"] }
itertools = "0.10"
kafka = { version = "0.9", default-features = false }
pulldown-cmark = "0.9"
redis = "0.22"
regex = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "2"
serde_yaml = "0.9"
tempfile = "3"
workspace-hack = { path = "../workspace-hack" }
yaml-rust = "0.4"
