version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: [ "postgres", "-c", "wal_level=logical" ]

  mysql:
    image: mysql:8.0
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p123456" ]
      interval: 5s
      timeout: 5s
      retries: 5

  source-test-env:
    image: public.ecr.aws/x5u3w5h6/rw-build-env:v20221212
    depends_on:
      - mysql
      - db
    volumes:
      - ..:/risingwave

  sink-test-env:
    image: public.ecr.aws/x5u3w5h6/rw-build-env:v20221212
    depends_on:
      - mysql
      - db
    volumes:
      - ..:/risingwave

  rw-build-env:
    image: public.ecr.aws/x5u3w5h6/rw-build-env:v20221212
    volumes:
      - ..:/risingwave

  regress-test-env:
    image: public.ecr.aws/x5u3w5h6/rw-build-env:v20221212
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ..:/risingwave

  release-env:
    image: quay.io/pypa/manylinux2014_x86_64
    working_dir: /mnt
    volumes:
      - ..:/mnt
