[package]
name = "workspace-config"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Use a feature flag to control enable or not, otherwise `cargo test` will compile all dependencies.
enable-static-link = ["isahc", "openssl", "rdkafka"]
enable-static-log-level = ["log", "tracing"]

[dependencies]
isahc = { version = "1", optional = true, default-features = false, features = ["static-ssl", "static-curl"] }
log = { version = "0.4", optional = true, features = ["release_max_level_info"] }
openssl = { version = "0.10", optional = true, features = ["vendored"] }
rdkafka = { package = "madsim-rdkafka", version = "=0.2.8-alpha", optional = true, features = ["ssl-vendored", "gssapi-vendored"] }
tracing = { version = "0.1", optional = true, features = ["release_max_level_info"] }
# workspace-hack = { path = "../../workspace-hack" }
# Don't add workspace-hack into this crate!
