[package]
name = "risingwave_storage"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1"
arc-swap = "1"
async-trait = "0.1"
async_stack_trace = { path = "../utils/async_stack_trace" }
auto_enums = { version = "0.7", features = ["futures"] }
bitvec = "1"
byteorder = "1"
bytes = { version = "1", features = ["serde"] }
chrono = { version = "0.4", default-features = false, features = [
    "clock",
    "std",
] }
crc32fast = "1"
crossbeam = "0.8.1"
dashmap = { version = "5", default-features = false }
dyn-clone = "1.0.4"
either = "1"
enum-as-inner = "0.5"
fail = "0.5"
farmhash = "1"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
futures-async-stream = "0.2"
hyper = "0.14"
itertools = "0.10"
libc = "0.2"
lz4 = "1.23.1"
memcomparable = { path = "../utils/memcomparable" }
minitrace = "0.4"
minstant = "0.1"
nix = { version = "0.25", features = ["fs", "mman"] }
num-integer = "0.1"
num-traits = "0.2"
parking_lot = "0.12"
paste = "1"
prometheus = { version = "0.13", features = ["process"] }
prost = "0.11"
rand = "0.8"
regex = "1"
risingwave_common = { path = "../common" }
risingwave_common_service = { path = "../common/common_service" }
risingwave_hummock_sdk = { path = "../storage/hummock_sdk" }
risingwave_hummock_trace = { path = "../storage/hummock_trace", optional = true }
risingwave_object_store = { path = "../object_store" }
risingwave_pb = { path = "../prost" }
risingwave_rpc_client = { path = "../rpc_client" }
scopeguard = "1"
# rocksdb = { git = "https://github.com/tikv/rust-rocksdb.git", rev = "fa83ff19", features = [
#     "encryption",
#     "static_libcpp",
# ], optional = true }
serde = { version = "1", features = ["derive"] }
smallvec = "1"
spin = "0.9"
sync-point = { path = "../utils/sync-point" }
tempfile = "3"
thiserror = "1"
# tikv-client = { git = "https://github.com/tikv/client-rust", rev = "5714b2", optional = true }
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "fs",
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-metrics = "0.1.0"
tokio-retry = "0.3"
tokio-stream = "0.1"
tonic = { version = "0.2", package = "madsim-tonic" }
tracing = "0.1"
twox-hash = "1"
zstd = "0.11.2"

[target.'cfg(hm_trace)'.dependencies]
risingwave_hummock_trace = { path = "../storage/hummock_trace" }

[target.'cfg(not(madsim))'.dependencies]
risingwave_tracing = { path = "../tracing" }
workspace-hack = { path = "../workspace-hack" }

[dev-dependencies]
criterion = { version = "0.4", features = ["async_futures"] }
moka = { version = "0.9", features = ["future"] }
risingwave_test_runner = { path = "../test_runner" }
uuid = { version = "1", features = ["v4"] }

[target.'cfg(target_os = "linux")'.dev-dependencies]
fiemap = "0.1.1"

[features]
# rocksdb-local = ["rocksdb"]
# tikv = ["tikv-client"]
test = []
failpoints = ["fail/failpoints"]
bpf = []
hm-trace = ["risingwave_hummock_trace"]

[[bench]]
name = "bench_block_iter"
harness = false
# Enable debug if you want to generate flamegraph.
# debug = true

[[bench]]
name = "bench_lru_cache"
harness = false

[[bench]]
name = "bench_merge_iter"
harness = false

[[bench]]
name = "bench_fs_operation"
harness = false

[[bench]]
name = "bench_compression"
harness = false

[[bench]]
name = "bench_compactor"
harness = false

[[bench]]
name = "bench_multi_builder"
harness = false
