[package]
name = "risingwave_rpc_client"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1"
async-trait = "0.1"
async_stack_trace = { path = "../utils/async_stack_trace" }
futures = { version = "0.3", default-features = false, features = ["alloc"] }
paste = "1"
rand = "0.8"
risingwave_common = { path = "../common" }
risingwave_hummock_sdk = { path = "../storage/hummock_sdk" }
risingwave_pb = { path = "../prost" }
thiserror = "1"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
] }
tokio-retry = "0.3"
tokio-stream = "0.1"
tonic = { version = "0.2", package = "madsim-tonic" }
tracing = "0.1"

[target.'cfg(not(madsim))'.dependencies]
moka = { version = "0.9", features = ["future"] }
workspace-hack = { path = "../workspace-hack" }
